export default {
  input: 'dist/esm/index.js',
  output: [
    {
      file: 'dist/plugin.js',
      format: 'iife',
      name: 'capacitorBiometricAuth',
      globals: {
        '@capacitor/core': 'capacitorExports',
        '@capacitor/app': 'app',
        '@aparajita/capacitor-native-decorator': 'capacitorNativeDecorator'
      },
      sourcemap: true,
      inlineDynamicImports: true
    },
    {
      file: 'dist/plugin.cjs.js',
      format: 'cjs',
      sourcemap: true,
      inlineDynamicImports: true
    }
  ],
  external: [
    '@capacitor/app',
    '@capacitor/core',
    '@aparajita/capacitor-native-decorator'
  ],

  // This is for the code generated by decorators. If we don't specify this,
  // it defaults to globalThis, which older android phones won't understand.
  context: 'window'
}
